# Generated by Django 4.2.1 on 2024-03-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="image",
            field=models.FileField(blank=True, upload_to="project_images/"),
        ),
    ]
